stages:
  -  deploy_stp_fe

cache:
  paths:
    - node_modules/

deploy:
  image: ubuntu:latest
  stage:  deploy_stp_fe
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - echo "$SSH_USER"
    - echo "$SSH_HOST"
    - echo "$PROJECT_DIR"
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST -p 1903 "cd $PROJECT_DIR && git pull origin master"
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST -p 1903 "cd $PROJECT_DIR && docker compose down -v && docker compose up --force-recreate --build -d && docker buildx prune -f"
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST -p 1903 "docker exec nginx nginx -s reload"
  only:
    - master