export const tableData = [
  {
    feed: 'a',
    phase: 'Starter',
    feedSizePhase: 'Refined Flour',
    feedSizeDiameter: '-',
    netWeight: 25,
    moistureContent: 11,
    protein: 36,
    fat: 7,
    crudeFiber: 3,
    ash: 12,
    energy: 17,
  },
  {
    feed: 'b',
    phase: 'Starter',
    feedSizePhase: 'Crumble',
    feedSizeDiameter: '0.4 - 0.8',
    netWeight: 25,
    moistureContent: 11,
    protein: 36,
    fat: 7,
    crudeFiber: 3,
    ash: 12,
    energy: 17,
  },
  {
    feed: 'c',
    phase: 'Starter',
    feedSizePhase: 'Pellets',
    feedSizeDiameter: '1.0x1.0-1.8',
    netWeight: 25,
    moistureContent: 11,
    protein: 36,
    fat: 7,
    crudeFiber: 3,
    ash: 12,
    energy: 17,
  },
  {
    feed: 'd',
    phase: 'Starter',
    feedSizePhase: 'Pellets',
    feedSizeDiameter: '1.2x1.2-2.0',
    netWeight: 25,
    moistureContent: 11,
    protein: 36,
    fat: 7,
    crudeFiber: 3,
    ash: 12,
    energy: 17,
  },
  {
    feed: 'e',
    phase: 'Grower',
    feedSizePhase: 'Pellets',
    feedSizeDiameter: '1.2x1.2-2.0',
    netWeight: 25,
    moistureContent: 11,
    protein: 32,
    fat: 6,
    crudeFiber: 3,
    ash: 12,
    energy: 16.5,
  },
]
